### ISSUE TITLE
Styled Markup Feedback!

### ISSUE THREAD

**Issue by mfehrenbach** [AmyLew15/Manuscript#3]
- [x] #5

     https://github.com/AmyLew15/Manuscript/blob/996f4eac1bba0020e2fee25e8bec9f2ce96d804b/index.html#L14-L16

- [x] I’d like to see some _much_ more inline semantic considerations within all the `p`—some `q`, `em`, `strong`, `cite`, add some links, etc. Pick some `blockquote` out to draw me in. Think of them as a way to add visual interest, down the page. There are too many “blank” grafs and that doesn’t make you want to get into the text/response!

- [x] You have good fundamentals here on semantic structure—but now it is asking for them to be used more for styles! Differentiate/add hierarchy with the “boxes” you’ve set up. This [`style.css`](https://github.com/AmyLew15/Manuscript/blob/main/style.css) is pretty sparse.

- [x] Body copy size is a bit small for me. I think it also wants shorter line lengths, and some increased `line-height` to give it some breathing room.

    <img width="958" alt="image" src="https://github.com/user-attachments/assets/1cba2989-3d86-43d0-a5bd-5b013924f288">

- [x] The overall “volume” is too even—and I think it would benefit from much more visual contrast, here—_much_ more distance between the base `p` and `h1`. The heading could be some 4–8x larger.

- [x] #4

    <img width="1025" alt="image" src="https://github.com/user-attachments/assets/f9eb8c52-243d-4d7b-b790-62ed044fe99e">

    I think this could use more [“front matter”](https://www.scribendi.com/academy/articles/front_matter.en.html). Give us a heading, your name, etc. These will also give you more things to style and add interest with (after adding more to the texts themselves)!

Overall, a good start here but now we really want to see this taken much further this week! 

✊

**Comment by AmyLew15** [comment]
Took out sizing for headers and just made labels. Put headings into groups and added blockquotes and more "boxes"
